apiVersion: v2
appVersion: "9.0.1-2.2.1"
name: mysql-operator
description: MySQL Operator Helm Chart for deploying MySQL InnoDB Cluster in Kubernetes
type: application
version: "2.2.1"
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
